### ISSUE TITLE
There is no examples directory as linked in the README

### ISSUE THREAD

**Issue by baumgach** [StefanoWoerner/torchcross#1]

**Comment by StefanoWoerner** [comment]
Hi,
thanks for raising the issue! A large update to the library itself, but especially the documentation is coming Monday or Tuesday. The update will also contain some nice usage examples.

**Comment by StefanoWoerner** [comment]
Simple examples are now provided in the README. For a good real-world example, you can see [MIMeta](https://github.com/StefanoWoerner/mimeta-pytorch), which I also linked in the README.
@baumgach let me know what you think :)
