### ISSUE TITLE
No library documentation

### ISSUE THREAD

**Issue by thapaliya19** [StefanoWoerner/torchcross#2]
Can you provide some documentation on how to use the library? @StefanoWoerner

**Comment by StefanoWoerner** [comment]
Hi,
thanks for raising the issue! A large update to the library itself, but especially the documentation is coming Monday or Tuesday. The update will also contain some nice usage examples.

**Comment by StefanoWoerner** [comment]
@thapaliya19 the update is finally here. I added simple examples in the README. For a good real-world example, you can see [MIMeta](https://github.com/StefanoWoerner/mimeta-pytorch), which I also linked in the README, as well as its examples.

Any feedback is welcome. Let me know what you think :)

**Comment by StefanoWoerner** [comment]
I plan to add a more extensive documentation on readthedocs soon. See #3.
